apiVersion: batch/v1
kind: Job
metadata:
  name: first-job
spec:
  completions: 5 # Number of successful Pods to complete jobs or task
  parallelism: 2 # Number of pods at a time, default 1, and if set to "0" then the Job is effectively paused until it is increased
  backoffLimit: 10 # Limit of retries before marking job as Failed
  template:
    spec:
      containers:
      - name: random
        image: kodekloud/random-error
      restartPolicy: Never # OnFailure

