apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-d
  name: nginx-d
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-d
  template:
    metadata:
      labels:
        app: nginx-d
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80